/*
Kable API

The Kable API allows developers to manage customers, plans, and usage data for their API.  ## API Host and Environments  Kable is accessible in Live and Test environments for authentication and metering of client API requests. You will have separate API keys to access each environment.  You should only use Kable's Live environment for your own production data. All other configured environments should use Kable's Test environment.  ## API Protocols and Headers  All requests to the Kable API are made over HTTPS TLS v1.2+ to ensure security. Calls made over HTTP will fail. Any requests without proper authentication will also fail.  The Kable API uses standard JSON for requests and responses. Be sure to set both the `Content-Type` and `Accept` headers on each request to `application/json`.  Each Kable API response includes a `requestId` as the `X-REQUEST-ID` response header. The `requestId` is included on most responses regardless whether the API request succeeded or failed. You can use this `requestId` to help with debugging or when contacting support regarding a specific API call.  ## API Versioning  All Kable endpoints are versioned. After the host, each API can be found at `/api/vX/...` where X is the API version.  We strive to ensure that changes to the Kable API are backward compatible. Sometimes, though, we must break from older design paradigms to make the product better. When this happens, a new version of the API is released.  The current version of the Kable API is `v1`.  

API version: 1.0.0
Contact: contact@kable.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InvoiceLineItemTierResponseDtoPrice The price of the line item.
type InvoiceLineItemTierResponseDtoPrice struct {
	// Three-letter ISO currency code
	Currency string `json:"currency"`
	// The total price amount.
	Amount float32 `json:"amount"`
}

// NewInvoiceLineItemTierResponseDtoPrice instantiates a new InvoiceLineItemTierResponseDtoPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvoiceLineItemTierResponseDtoPrice(currency string, amount float32) *InvoiceLineItemTierResponseDtoPrice {
	this := InvoiceLineItemTierResponseDtoPrice{}
	this.Currency = currency
	this.Amount = amount
	return &this
}

// NewInvoiceLineItemTierResponseDtoPriceWithDefaults instantiates a new InvoiceLineItemTierResponseDtoPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvoiceLineItemTierResponseDtoPriceWithDefaults() *InvoiceLineItemTierResponseDtoPrice {
	this := InvoiceLineItemTierResponseDtoPrice{}
	return &this
}

// GetCurrency returns the Currency field value
func (o *InvoiceLineItemTierResponseDtoPrice) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *InvoiceLineItemTierResponseDtoPrice) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *InvoiceLineItemTierResponseDtoPrice) SetCurrency(v string) {
	o.Currency = v
}

// GetAmount returns the Amount field value
func (o *InvoiceLineItemTierResponseDtoPrice) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *InvoiceLineItemTierResponseDtoPrice) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *InvoiceLineItemTierResponseDtoPrice) SetAmount(v float32) {
	o.Amount = v
}

func (o InvoiceLineItemTierResponseDtoPrice) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["currency"] = o.Currency
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableInvoiceLineItemTierResponseDtoPrice struct {
	value *InvoiceLineItemTierResponseDtoPrice
	isSet bool
}

func (v NullableInvoiceLineItemTierResponseDtoPrice) Get() *InvoiceLineItemTierResponseDtoPrice {
	return v.value
}

func (v *NullableInvoiceLineItemTierResponseDtoPrice) Set(val *InvoiceLineItemTierResponseDtoPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableInvoiceLineItemTierResponseDtoPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableInvoiceLineItemTierResponseDtoPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvoiceLineItemTierResponseDtoPrice(val *InvoiceLineItemTierResponseDtoPrice) *NullableInvoiceLineItemTierResponseDtoPrice {
	return &NullableInvoiceLineItemTierResponseDtoPrice{value: val, isSet: true}
}

func (v NullableInvoiceLineItemTierResponseDtoPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvoiceLineItemTierResponseDtoPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


