/*
Kable API

The Kable API allows developers to manage customers, plans, and usage data for their API.  ## API Host and Environments  Kable is accessible in Live and Test environments for authentication and metering of client API requests. You will have separate API keys to access each environment.  You should only use Kable's Live environment for your own production data. All other configured environments should use Kable's Test environment.  ## API Protocols and Headers  All requests to the Kable API are made over HTTPS TLS v1.2+ to ensure security. Calls made over HTTP will fail. Any requests without proper authentication will also fail.  The Kable API uses standard JSON for requests and responses. Be sure to set both the `Content-Type` and `Accept` headers on each request to `application/json`.  Each Kable API response includes a `requestId` as the `X-REQUEST-ID` response header. The `requestId` is included on most responses regardless whether the API request succeeded or failed. You can use this `requestId` to help with debugging or when contacting support regarding a specific API call.  ## API Versioning  All Kable endpoints are versioned. After the host, each API can be found at `/api/vX/...` where X is the API version.  We strive to ensure that changes to the Kable API are backward compatible. Sometimes, though, we must break from older design paradigms to make the product better. When this happens, a new version of the API is released.  The current version of the Kable API is `v1`.  

API version: 1.0.0
Contact: contact@kable.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UsageMetricIntervalResponseDtoDimension The dimension for which usage was evaluated.
type UsageMetricIntervalResponseDtoDimension struct {
	// A Kable-defined identifier for the dimension.
	DimensionId string `json:"dimensionId"`
	// An identifier for the dimension defined by you. This key corresponds to the key in the JSON payload of a usage event, and can be passed into the `record` library method.
	Key string `json:"key"`
	// A human-readable name for the dimension, visible on dashboards, invoices, and reports.
	Name string `json:"name"`
}

// NewUsageMetricIntervalResponseDtoDimension instantiates a new UsageMetricIntervalResponseDtoDimension object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsageMetricIntervalResponseDtoDimension(dimensionId string, key string, name string) *UsageMetricIntervalResponseDtoDimension {
	this := UsageMetricIntervalResponseDtoDimension{}
	this.DimensionId = dimensionId
	this.Key = key
	this.Name = name
	return &this
}

// NewUsageMetricIntervalResponseDtoDimensionWithDefaults instantiates a new UsageMetricIntervalResponseDtoDimension object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsageMetricIntervalResponseDtoDimensionWithDefaults() *UsageMetricIntervalResponseDtoDimension {
	this := UsageMetricIntervalResponseDtoDimension{}
	return &this
}

// GetDimensionId returns the DimensionId field value
func (o *UsageMetricIntervalResponseDtoDimension) GetDimensionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DimensionId
}

// GetDimensionIdOk returns a tuple with the DimensionId field value
// and a boolean to check if the value has been set.
func (o *UsageMetricIntervalResponseDtoDimension) GetDimensionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DimensionId, true
}

// SetDimensionId sets field value
func (o *UsageMetricIntervalResponseDtoDimension) SetDimensionId(v string) {
	o.DimensionId = v
}

// GetKey returns the Key field value
func (o *UsageMetricIntervalResponseDtoDimension) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *UsageMetricIntervalResponseDtoDimension) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *UsageMetricIntervalResponseDtoDimension) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value
func (o *UsageMetricIntervalResponseDtoDimension) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UsageMetricIntervalResponseDtoDimension) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UsageMetricIntervalResponseDtoDimension) SetName(v string) {
	o.Name = v
}

func (o UsageMetricIntervalResponseDtoDimension) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["dimensionId"] = o.DimensionId
	}
	if true {
		toSerialize["key"] = o.Key
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableUsageMetricIntervalResponseDtoDimension struct {
	value *UsageMetricIntervalResponseDtoDimension
	isSet bool
}

func (v NullableUsageMetricIntervalResponseDtoDimension) Get() *UsageMetricIntervalResponseDtoDimension {
	return v.value
}

func (v *NullableUsageMetricIntervalResponseDtoDimension) Set(val *UsageMetricIntervalResponseDtoDimension) {
	v.value = val
	v.isSet = true
}

func (v NullableUsageMetricIntervalResponseDtoDimension) IsSet() bool {
	return v.isSet
}

func (v *NullableUsageMetricIntervalResponseDtoDimension) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsageMetricIntervalResponseDtoDimension(val *UsageMetricIntervalResponseDtoDimension) *NullableUsageMetricIntervalResponseDtoDimension {
	return &NullableUsageMetricIntervalResponseDtoDimension{value: val, isSet: true}
}

func (v NullableUsageMetricIntervalResponseDtoDimension) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsageMetricIntervalResponseDtoDimension) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


