/*
Kable API

The Kable API allows developers to manage customers, plans, and usage data for their API.  ## API Host and Environments  Kable is accessible in Live and Test environments for authentication and metering of client API requests. You will have separate API keys to access each environment.  You should only use Kable's Live environment for your own production data. All other configured environments should use Kable's Test environment.  ## API Protocols and Headers  All requests to the Kable API are made over HTTPS TLS v1.2+ to ensure security. Calls made over HTTP will fail. Any requests without proper authentication will also fail.  The Kable API uses standard JSON for requests and responses. Be sure to set both the `Content-Type` and `Accept` headers on each request to `application/json`.  Each Kable API response includes a `requestId` as the `X-REQUEST-ID` response header. The `requestId` is included on most responses regardless whether the API request succeeded or failed. You can use this `requestId` to help with debugging or when contacting support regarding a specific API call.  ## API Versioning  All Kable endpoints are versioned. After the host, each API can be found at `/api/vX/...` where X is the API version.  We strive to ensure that changes to the Kable API are backward compatible. Sometimes, though, we must break from older design paradigms to make the product better. When this happens, a new version of the API is released.  The current version of the Kable API is `v1`.  

API version: 1.0.0
Contact: contact@kable.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreatePlanRequestDto struct for CreatePlanRequestDto
type CreatePlanRequestDto struct {
	PlanId string `json:"planId"`
	// A human-readable name for the plan, visible on dashboards, invoices, and reports.
	Name string `json:"name"`
	// An identifier for the plan as defined by your API.
	ExternalId *string `json:"externalId,omitempty"`
	// A human-readable description for the plan, visible on dashboards, invoices, and reports.
	Description *string `json:"description,omitempty"`
	// An additional identifier for the plan, defined by you, that is *not* visible to customers. If you have different *Monthly Active Users Plan*s for different cohorts of customers, this is a useful place to differentiate those.
	Nickname *string `json:"nickname,omitempty"`
	// The type of plan.
	Type string `json:"type"`
	// An identifier of the dimension along which usage is aggregated in this plan.
	DimensionId *string `json:"dimensionId,omitempty"`
	// The aggregation along which usage metrics are calculated in this plan, relevant only for usage plans.
	Aggregation *string `json:"aggregation,omitempty"`
	// The billing interval for the plan.
	Interval *string `json:"interval,omitempty"`
	// Arbitrary key-value pairs to attach to the object that can be useful for controlling functionality inside your API.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Price CreatePlanRequestDtoPrice `json:"price"`
}

// NewCreatePlanRequestDto instantiates a new CreatePlanRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlanRequestDto(planId string, name string, type_ string, price CreatePlanRequestDtoPrice) *CreatePlanRequestDto {
	this := CreatePlanRequestDto{}
	this.PlanId = planId
	this.Name = name
	this.Type = type_
	this.Price = price
	return &this
}

// NewCreatePlanRequestDtoWithDefaults instantiates a new CreatePlanRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlanRequestDtoWithDefaults() *CreatePlanRequestDto {
	this := CreatePlanRequestDto{}
	return &this
}

// GetPlanId returns the PlanId field value
func (o *CreatePlanRequestDto) GetPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *CreatePlanRequestDto) SetPlanId(v string) {
	o.PlanId = v
}

// GetName returns the Name field value
func (o *CreatePlanRequestDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreatePlanRequestDto) SetName(v string) {
	o.Name = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *CreatePlanRequestDto) GetExternalId() string {
	if o == nil || o.ExternalId == nil {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetExternalIdOk() (*string, bool) {
	if o == nil || o.ExternalId == nil {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *CreatePlanRequestDto) HasExternalId() bool {
	if o != nil && o.ExternalId != nil {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *CreatePlanRequestDto) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreatePlanRequestDto) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreatePlanRequestDto) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreatePlanRequestDto) SetDescription(v string) {
	o.Description = &v
}

// GetNickname returns the Nickname field value if set, zero value otherwise.
func (o *CreatePlanRequestDto) GetNickname() string {
	if o == nil || o.Nickname == nil {
		var ret string
		return ret
	}
	return *o.Nickname
}

// GetNicknameOk returns a tuple with the Nickname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetNicknameOk() (*string, bool) {
	if o == nil || o.Nickname == nil {
		return nil, false
	}
	return o.Nickname, true
}

// HasNickname returns a boolean if a field has been set.
func (o *CreatePlanRequestDto) HasNickname() bool {
	if o != nil && o.Nickname != nil {
		return true
	}

	return false
}

// SetNickname gets a reference to the given string and assigns it to the Nickname field.
func (o *CreatePlanRequestDto) SetNickname(v string) {
	o.Nickname = &v
}

// GetType returns the Type field value
func (o *CreatePlanRequestDto) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreatePlanRequestDto) SetType(v string) {
	o.Type = v
}

// GetDimensionId returns the DimensionId field value if set, zero value otherwise.
func (o *CreatePlanRequestDto) GetDimensionId() string {
	if o == nil || o.DimensionId == nil {
		var ret string
		return ret
	}
	return *o.DimensionId
}

// GetDimensionIdOk returns a tuple with the DimensionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetDimensionIdOk() (*string, bool) {
	if o == nil || o.DimensionId == nil {
		return nil, false
	}
	return o.DimensionId, true
}

// HasDimensionId returns a boolean if a field has been set.
func (o *CreatePlanRequestDto) HasDimensionId() bool {
	if o != nil && o.DimensionId != nil {
		return true
	}

	return false
}

// SetDimensionId gets a reference to the given string and assigns it to the DimensionId field.
func (o *CreatePlanRequestDto) SetDimensionId(v string) {
	o.DimensionId = &v
}

// GetAggregation returns the Aggregation field value if set, zero value otherwise.
func (o *CreatePlanRequestDto) GetAggregation() string {
	if o == nil || o.Aggregation == nil {
		var ret string
		return ret
	}
	return *o.Aggregation
}

// GetAggregationOk returns a tuple with the Aggregation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetAggregationOk() (*string, bool) {
	if o == nil || o.Aggregation == nil {
		return nil, false
	}
	return o.Aggregation, true
}

// HasAggregation returns a boolean if a field has been set.
func (o *CreatePlanRequestDto) HasAggregation() bool {
	if o != nil && o.Aggregation != nil {
		return true
	}

	return false
}

// SetAggregation gets a reference to the given string and assigns it to the Aggregation field.
func (o *CreatePlanRequestDto) SetAggregation(v string) {
	o.Aggregation = &v
}

// GetInterval returns the Interval field value if set, zero value otherwise.
func (o *CreatePlanRequestDto) GetInterval() string {
	if o == nil || o.Interval == nil {
		var ret string
		return ret
	}
	return *o.Interval
}

// GetIntervalOk returns a tuple with the Interval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetIntervalOk() (*string, bool) {
	if o == nil || o.Interval == nil {
		return nil, false
	}
	return o.Interval, true
}

// HasInterval returns a boolean if a field has been set.
func (o *CreatePlanRequestDto) HasInterval() bool {
	if o != nil && o.Interval != nil {
		return true
	}

	return false
}

// SetInterval gets a reference to the given string and assigns it to the Interval field.
func (o *CreatePlanRequestDto) SetInterval(v string) {
	o.Interval = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreatePlanRequestDto) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreatePlanRequestDto) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CreatePlanRequestDto) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPrice returns the Price field value
func (o *CreatePlanRequestDto) GetPrice() CreatePlanRequestDtoPrice {
	if o == nil {
		var ret CreatePlanRequestDtoPrice
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *CreatePlanRequestDto) GetPriceOk() (*CreatePlanRequestDtoPrice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *CreatePlanRequestDto) SetPrice(v CreatePlanRequestDtoPrice) {
	o.Price = v
}

func (o CreatePlanRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["planId"] = o.PlanId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.ExternalId != nil {
		toSerialize["externalId"] = o.ExternalId
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Nickname != nil {
		toSerialize["nickname"] = o.Nickname
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.DimensionId != nil {
		toSerialize["dimensionId"] = o.DimensionId
	}
	if o.Aggregation != nil {
		toSerialize["aggregation"] = o.Aggregation
	}
	if o.Interval != nil {
		toSerialize["interval"] = o.Interval
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if true {
		toSerialize["price"] = o.Price
	}
	return json.Marshal(toSerialize)
}

type NullableCreatePlanRequestDto struct {
	value *CreatePlanRequestDto
	isSet bool
}

func (v NullableCreatePlanRequestDto) Get() *CreatePlanRequestDto {
	return v.value
}

func (v *NullableCreatePlanRequestDto) Set(val *CreatePlanRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlanRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlanRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlanRequestDto(val *CreatePlanRequestDto) *NullableCreatePlanRequestDto {
	return &NullableCreatePlanRequestDto{value: val, isSet: true}
}

func (v NullableCreatePlanRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlanRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


