/*
Kable API

The Kable API allows developers to manage customers, plans, and usage data for their API.  ## API Host and Environments  Kable is accessible in Live and Test environments for authentication and metering of client API requests. You will have separate API keys to access each environment.  You should only use Kable's Live environment for your own production data. All other configured environments should use Kable's Test environment.  ## API Protocols and Headers  All requests to the Kable API are made over HTTPS TLS v1.2+ to ensure security. Calls made over HTTP will fail. Any requests without proper authentication will also fail.  The Kable API uses standard JSON for requests and responses. Be sure to set both the `Content-Type` and `Accept` headers on each request to `application/json`.  Each Kable API response includes a `requestId` as the `X-REQUEST-ID` response header. The `requestId` is included on most responses regardless whether the API request succeeded or failed. You can use this `requestId` to help with debugging or when contacting support regarding a specific API call.  ## API Versioning  All Kable endpoints are versioned. After the host, each API can be found at `/api/vX/...` where X is the API version.  We strive to ensure that changes to the Kable API are backward compatible. Sometimes, though, we must break from older design paradigms to make the product better. When this happens, a new version of the API is released.  The current version of the Kable API is `v1`.  

API version: 1.0.0
Contact: contact@kable.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// UpdateBundleRequestDto struct for UpdateBundleRequestDto
type UpdateBundleRequestDto struct {
	BundleId *string `json:"bundleId,omitempty"`
	Name *string `json:"name,omitempty"`
	ExternalId *string `json:"externalId,omitempty"`
	Description *string `json:"description,omitempty"`
	Nickname *string `json:"nickname,omitempty"`
	PlanIds []string `json:"planIds,omitempty"`
	Currency *string `json:"currency,omitempty"`
	CostPerCredit *float32 `json:"costPerCredit,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

// NewUpdateBundleRequestDto instantiates a new UpdateBundleRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBundleRequestDto() *UpdateBundleRequestDto {
	this := UpdateBundleRequestDto{}
	return &this
}

// NewUpdateBundleRequestDtoWithDefaults instantiates a new UpdateBundleRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBundleRequestDtoWithDefaults() *UpdateBundleRequestDto {
	this := UpdateBundleRequestDto{}
	return &this
}

// GetBundleId returns the BundleId field value if set, zero value otherwise.
func (o *UpdateBundleRequestDto) GetBundleId() string {
	if o == nil || o.BundleId == nil {
		var ret string
		return ret
	}
	return *o.BundleId
}

// GetBundleIdOk returns a tuple with the BundleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBundleRequestDto) GetBundleIdOk() (*string, bool) {
	if o == nil || o.BundleId == nil {
		return nil, false
	}
	return o.BundleId, true
}

// HasBundleId returns a boolean if a field has been set.
func (o *UpdateBundleRequestDto) HasBundleId() bool {
	if o != nil && o.BundleId != nil {
		return true
	}

	return false
}

// SetBundleId gets a reference to the given string and assigns it to the BundleId field.
func (o *UpdateBundleRequestDto) SetBundleId(v string) {
	o.BundleId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateBundleRequestDto) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBundleRequestDto) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateBundleRequestDto) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateBundleRequestDto) SetName(v string) {
	o.Name = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *UpdateBundleRequestDto) GetExternalId() string {
	if o == nil || o.ExternalId == nil {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBundleRequestDto) GetExternalIdOk() (*string, bool) {
	if o == nil || o.ExternalId == nil {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *UpdateBundleRequestDto) HasExternalId() bool {
	if o != nil && o.ExternalId != nil {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *UpdateBundleRequestDto) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateBundleRequestDto) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBundleRequestDto) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateBundleRequestDto) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateBundleRequestDto) SetDescription(v string) {
	o.Description = &v
}

// GetNickname returns the Nickname field value if set, zero value otherwise.
func (o *UpdateBundleRequestDto) GetNickname() string {
	if o == nil || o.Nickname == nil {
		var ret string
		return ret
	}
	return *o.Nickname
}

// GetNicknameOk returns a tuple with the Nickname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBundleRequestDto) GetNicknameOk() (*string, bool) {
	if o == nil || o.Nickname == nil {
		return nil, false
	}
	return o.Nickname, true
}

// HasNickname returns a boolean if a field has been set.
func (o *UpdateBundleRequestDto) HasNickname() bool {
	if o != nil && o.Nickname != nil {
		return true
	}

	return false
}

// SetNickname gets a reference to the given string and assigns it to the Nickname field.
func (o *UpdateBundleRequestDto) SetNickname(v string) {
	o.Nickname = &v
}

// GetPlanIds returns the PlanIds field value if set, zero value otherwise.
func (o *UpdateBundleRequestDto) GetPlanIds() []string {
	if o == nil || o.PlanIds == nil {
		var ret []string
		return ret
	}
	return o.PlanIds
}

// GetPlanIdsOk returns a tuple with the PlanIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBundleRequestDto) GetPlanIdsOk() ([]string, bool) {
	if o == nil || o.PlanIds == nil {
		return nil, false
	}
	return o.PlanIds, true
}

// HasPlanIds returns a boolean if a field has been set.
func (o *UpdateBundleRequestDto) HasPlanIds() bool {
	if o != nil && o.PlanIds != nil {
		return true
	}

	return false
}

// SetPlanIds gets a reference to the given []string and assigns it to the PlanIds field.
func (o *UpdateBundleRequestDto) SetPlanIds(v []string) {
	o.PlanIds = v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *UpdateBundleRequestDto) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBundleRequestDto) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *UpdateBundleRequestDto) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *UpdateBundleRequestDto) SetCurrency(v string) {
	o.Currency = &v
}

// GetCostPerCredit returns the CostPerCredit field value if set, zero value otherwise.
func (o *UpdateBundleRequestDto) GetCostPerCredit() float32 {
	if o == nil || o.CostPerCredit == nil {
		var ret float32
		return ret
	}
	return *o.CostPerCredit
}

// GetCostPerCreditOk returns a tuple with the CostPerCredit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBundleRequestDto) GetCostPerCreditOk() (*float32, bool) {
	if o == nil || o.CostPerCredit == nil {
		return nil, false
	}
	return o.CostPerCredit, true
}

// HasCostPerCredit returns a boolean if a field has been set.
func (o *UpdateBundleRequestDto) HasCostPerCredit() bool {
	if o != nil && o.CostPerCredit != nil {
		return true
	}

	return false
}

// SetCostPerCredit gets a reference to the given float32 and assigns it to the CostPerCredit field.
func (o *UpdateBundleRequestDto) SetCostPerCredit(v float32) {
	o.CostPerCredit = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *UpdateBundleRequestDto) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateBundleRequestDto) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UpdateBundleRequestDto) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *UpdateBundleRequestDto) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o UpdateBundleRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BundleId != nil {
		toSerialize["bundleId"] = o.BundleId
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.ExternalId != nil {
		toSerialize["externalId"] = o.ExternalId
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Nickname != nil {
		toSerialize["nickname"] = o.Nickname
	}
	if o.PlanIds != nil {
		toSerialize["planIds"] = o.PlanIds
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.CostPerCredit != nil {
		toSerialize["costPerCredit"] = o.CostPerCredit
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateBundleRequestDto struct {
	value *UpdateBundleRequestDto
	isSet bool
}

func (v NullableUpdateBundleRequestDto) Get() *UpdateBundleRequestDto {
	return v.value
}

func (v *NullableUpdateBundleRequestDto) Set(val *UpdateBundleRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBundleRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBundleRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBundleRequestDto(val *UpdateBundleRequestDto) *NullableUpdateBundleRequestDto {
	return &NullableUpdateBundleRequestDto{value: val, isSet: true}
}

func (v NullableUpdateBundleRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBundleRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


