/*
Kable API

The Kable API allows developers to manage customers, plans, and usage data for their API.  ## API Host and Environments  Kable is accessible in Live and Test environments for authentication and metering of client API requests. You will have separate API keys to access each environment.  You should only use Kable's Live environment for your own production data. All other configured environments should use Kable's Test environment.  ## API Protocols and Headers  All requests to the Kable API are made over HTTPS TLS v1.2+ to ensure security. Calls made over HTTP will fail. Any requests without proper authentication will also fail.  The Kable API uses standard JSON for requests and responses. Be sure to set both the `Content-Type` and `Accept` headers on each request to `application/json`.  Each Kable API response includes a `requestId` as the `X-REQUEST-ID` response header. The `requestId` is included on most responses regardless whether the API request succeeded or failed. You can use this `requestId` to help with debugging or when contacting support regarding a specific API call.  ## API Versioning  All Kable endpoints are versioned. After the host, each API can be found at `/api/vX/...` where X is the API version.  We strive to ensure that changes to the Kable API are backward compatible. Sometimes, though, we must break from older design paradigms to make the product better. When this happens, a new version of the API is released.  The current version of the Kable API is `v1`.  

API version: 1.0.0
Contact: contact@kable.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PlanEntitlementRequestDto struct for PlanEntitlementRequestDto
type PlanEntitlementRequestDto struct {
	// The entitlement to assign.
	EntitlementId string `json:"entitlementId"`
	// The value of the entitlement.
	Value map[string]interface{} `json:"value"`
}

// NewPlanEntitlementRequestDto instantiates a new PlanEntitlementRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanEntitlementRequestDto(entitlementId string, value map[string]interface{}) *PlanEntitlementRequestDto {
	this := PlanEntitlementRequestDto{}
	this.EntitlementId = entitlementId
	this.Value = value
	return &this
}

// NewPlanEntitlementRequestDtoWithDefaults instantiates a new PlanEntitlementRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanEntitlementRequestDtoWithDefaults() *PlanEntitlementRequestDto {
	this := PlanEntitlementRequestDto{}
	return &this
}

// GetEntitlementId returns the EntitlementId field value
func (o *PlanEntitlementRequestDto) GetEntitlementId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntitlementId
}

// GetEntitlementIdOk returns a tuple with the EntitlementId field value
// and a boolean to check if the value has been set.
func (o *PlanEntitlementRequestDto) GetEntitlementIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntitlementId, true
}

// SetEntitlementId sets field value
func (o *PlanEntitlementRequestDto) SetEntitlementId(v string) {
	o.EntitlementId = v
}

// GetValue returns the Value field value
func (o *PlanEntitlementRequestDto) GetValue() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *PlanEntitlementRequestDto) GetValueOk() (map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *PlanEntitlementRequestDto) SetValue(v map[string]interface{}) {
	o.Value = v
}

func (o PlanEntitlementRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["entitlementId"] = o.EntitlementId
	}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullablePlanEntitlementRequestDto struct {
	value *PlanEntitlementRequestDto
	isSet bool
}

func (v NullablePlanEntitlementRequestDto) Get() *PlanEntitlementRequestDto {
	return v.value
}

func (v *NullablePlanEntitlementRequestDto) Set(val *PlanEntitlementRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanEntitlementRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanEntitlementRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanEntitlementRequestDto(val *PlanEntitlementRequestDto) *NullablePlanEntitlementRequestDto {
	return &NullablePlanEntitlementRequestDto{value: val, isSet: true}
}

func (v NullablePlanEntitlementRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanEntitlementRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


